service: btc-data-tracker

frameworkVersion: '3'


provider:
  name: aws
  runtime: python3.8

functions:
  rateHandler:
    handler: handler.run
    events:
      # Invoke Lambda function every minute
      - schedule: rate(1 minute)
  getMetrics:
    handler: handler.getMetrics
    events:
      - httpApi:
          path: /
          method: get
