org: treyhay
app: btc-data-tracker
service: btc-data-tracker

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8

functions:
  rateHandler:
    handler: handler.run
    events:
      # Invoke Lambda function every minute
      - schedule: rate(1 minute)
    environment:
      INFLUX_TOKEN: ${param:influx_api_token}
      CRYPTO_TOKEN: ${param:crypto_api_token}
  getMetrics:
    handler: handler.getMetrics
    events:
      - httpApi:
          path: /metrics
          method: get
      - httpApi:
          path: /metrics/{metric}
          method: get
    environment:
      INFLUX_TOKEN: ${param:influx_api_token}
      CRYPTO_TOKEN: ${param:crypto_api_token}

plugins:
  - serverless-python-requirements